"""Disposable email domain blocklist — Part 4 of Bot Prevention Layer 0.

Maintains a set of 200+ known disposable/temporary email domains.
Lookup is O(1) via Python set membership testing.

Usage::

    from isg_agent.utils.disposable_emails import is_disposable_email

    if is_disposable_email("user@mailinator.com"):
        raise HTTPException(400, "Please use a permanent email address")

Environment variable override::

    ALLOWED_EMAIL_DOMAINS=mailinator.com,yopmail.com

When set, domains in this comma-separated list bypass the blocklist.
Useful for internal testing without disabling protection entirely.
"""

from __future__ import annotations

import logging
import os
from typing import Optional

__all__ = [
    "DISPOSABLE_DOMAINS",
    "is_disposable_email",
    "get_email_domain",
]

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Blocklist — 200+ known disposable / temporary email providers
# ---------------------------------------------------------------------------
# Sorted alphabetically for maintainability. Add new domains here.
# All domains are stored lowercase. Lookup is O(1).

DISPOSABLE_DOMAINS: frozenset[str] = frozenset(
    {
        # A
        "0815.ru",
        "10minutemail.com",
        "10minutemail.net",
        "10minutemail.org",
        "10minutemail.co.uk",
        "10minemail.com",
        "11mail.com",
        "20mail.eu",
        "20minutemail.com",
        "2prong.com",
        "33mail.com",
        "3d-painting.com",
        "a-bc.net",
        "agedmail.com",
        "agger.ro",
        "ajaxapp.net",
        "amail.com",
        "amail1.com",
        "antichef.com",
        "antichef.net",
        "antireg.com",
        "antireg.ru",
        "antispam.de",
        "antispammail.de",
        "armyspy.com",
        "aveocam.com",
        # B
        "beefmilk.com",
        "bigstring.com",
        "binkmail.com",
        "bio-muesli.net",
        "bladesy.com",
        "bmailer.me",
        "bobmail.info",
        "bodhi.lawlita.com",
        "bofthew.com",
        "bossmail.de",
        "boun.cr",
        "bouncr.com",
        "brasx.org",
        "breakthru.com",
        "brennendesreich.de",
        "broadbandninja.com",
        "bspamfree.org",
        "bugmenot.com",
        "bumpymail.com",
        "bund.us",
        "burnthespam.info",
        "burstmail.info",
        "buymoreplays.com",
        "byom.de",
        # C
        "cachedot.net",
        "casualdx.com",
        "cbsmail.net",
        "cek.pm",
        "cellurl.com",
        "chammy.info",
        "cheatmail.de",
        "chielo.com",
        "chogmail.com",
        "choicemail1.com",
        "clrmail.com",
        "cmail.club",
        "cmpmail.com",
        "coieo.com",
        "cool.fr.nf",
        "correo.blogos.net",
        "cosmorph.com",
        "courriel.fr.nf",
        "courrieltemporaire.com",
        "crazymailing.com",
        "cubiclink.com",
        "curryworld.de",
        "cust.in",
        "cuvox.de",
        # D
        "dacoolest.com",
        "dayrep.com",
        "dcemail.com",
        "deadaddress.com",
        "deadletter.ga",
        "delikkt.de",
        "despam.it",
        "despammed.com",
        "devnullmail.com",
        "dfgh.net",
        "diapaulfilms.com",
        "digitalsanctuary.com",
        "discardmail.com",
        "discardmail.de",
        "discard.email",
        "disposableaddress.com",
        "disposableemailaddresses.com",
        "disposableinbox.com",
        "dispostable.com",
        "dm.w3internet.co.uk",
        "dodgeit.com",
        "dodgit.com",
        "dodgit.org",
        "donemail.ru",
        "dontreg.com",
        "dontsendmespam.de",
        "drdrb.net",
        "drivetagdev.com",
        "dsiml.com",
        "dump-email.info",
        "dumpandfuck.com",
        "dumpmail.de",
        "dumpyemail.com",
        "durandinterstellar.com",
        # E
        "e4ward.com",
        "edgex.ru",
        "email60.com",
        "emaildienst.de",
        "emailias.com",
        "emailigo.de",
        "emailinfive.com",
        "emailisvalid.com",
        "emailmiser.com",
        "emailsensei.com",
        "emailtemporanea.com",
        "emailtemporanea.net",
        "emailtemporar.ro",
        "emailtemporary.com",
        "emailto.de",
        "emailwarden.com",
        "emailx.at.hm",
        "emailxfer.com",
        "emailz.cf",
        "emailz.ga",
        "emailz.gq",
        "emailz.ml",
        "emz.net",
        "enterto.com",
        "ephemail.net",
        "etgdev.de",
        # Note: example.com is IANA-reserved for documentation — NOT a disposable provider.
        # Do NOT add example.com here; it would break all existing tests that use test@example.com
        "explodemail.com",
        "express.net.ua",
        "eyepaste.com",
        # F
        "fakeinbox.com",
        "fakeinbox.info",
        "fakeinbox.net",
        "fakeinbox.org",
        "fakemailgenerator.com",
        "fakemailgenerator.net",
        "fastacura.com",
        "fastchevy.com",
        "fastchrysler.com",
        "fastkawasaki.com",
        "fastmazda.com",
        "fastmitsubishi.com",
        "fastnissan.com",
        "fastsubaru.com",
        "fastsuzuki.com",
        "fasttoyota.com",
        "fastyamaha.com",
        "filzmail.com",
        "fleckens.hu",
        "frapmail.com",
        "freundetreffen.de",
        "front14.org",
        "fuckingduh.com",
        "fux0ringduh.com",
        # G
        "garbagecollector.org",
        "garbagemail.org",
        "garciniacambogiareviews.ca",
        "gelitik.in",
        "get2mail.fr",
        "getairmail.com",
        "getmails.eu",
        "getonemail.com",
        "getonemail.net",
        "ghosttexter.de",
        "girlsundertheinfluence.com",
        "gishpuppy.com",
        "gmailnew.com",
        "goemailme.com",
        "gotmail.com",
        "gotmail.net",
        "gotmail.org",
        "grr.la",
        "gsrv.co.uk",
        "guerillamail.biz",
        "guerillamail.com",
        "guerillamail.de",
        "guerillamail.info",
        "guerillamail.net",
        "guerillamail.org",
        "guerillamailblock.com",
        "guerrillamail.biz",
        "guerrillamail.com",
        "guerrillamail.de",
        "guerrillamail.info",
        "guerrillamail.net",
        "guerrillamail.org",
        "guerrillamailblock.com",
        "gustr.com",
        # H
        "h.mintemail.com",
        "h8s.org",
        "haltospam.com",
        "harakirimail.com",
        "hat-geld.de",
        "hatespam.org",
        "herp.in",
        "hidemail.de",
        "hidzz.com",
        "hmamail.com",
        "hopemail.biz",
        "hostcelo.com",
        "hotpop.com",
        "humaility.com",
        # I
        "ieatspam.eu",
        "ieatspam.info",
        "ihateyoualot.info",
        "iheartspam.org",
        "ikbenspamvrij.nl",
        "imails.info",
        "inbax.tk",
        "inbox.si",
        "inboxalias.com",
        "inboxclean.com",
        "inboxclean.org",
        "inboxproxy.com",
        "incognitomail.com",
        "incognitomail.net",
        "incognitomail.org",
        "infocom.zp.ua",
        "insorg-mail.info",
        "instant-mail.de",
        "instantemailaddress.com",
        "ipoo.org",
        "irish2me.com",
        "iwi.net",
        # J - K
        "jetable.com",
        "jetable.fr.nf",
        "jetable.net",
        "jetable.org",
        "jnxjn.com",
        "josse.ltd",
        "junk.to",
        "junkmail.com",
        "junkmail.ga",
        "junkmail.gq",
        "kasmail.com",
        "kaspop.com",
        "keepmymail.com",
        "killmail.com",
        "killmail.net",
        "kir.ch.tc",
        "klassmaster.com",
        "klassmaster.net",
        "klassmaster.org",
        "klzlk.com",
        "koszmail.pl",
        "kurzepost.de",
        # L
        "lackmail.net",
        "lackmail.ru",
        "lags.us",
        "landmail.co",
        "lazyinbox.com",
        "letthemeatspam.com",
        "lhsdv.com",
        "lifecard.info",
        "lifebyfood.com",
        "link2mail.net",
        "litedrop.com",
        "lol.ovpn.to",
        "lolfreak.net",
        "lookugly.com",
        "lortemail.dk",
        "lr78.com",
        "lroid.com",
        "lukop.dk",
        # M
        "m21.cc",
        "mail-filter.com",
        "mail-temporaire.fr",
        "mail.by",
        "mail.mezimages.net",
        "mail1a.de",
        "mail21.cc",
        "mail2rss.org",
        "mail333.com",
        "mail4trash.com",
        "mailbidon.com",
        "mailblocks.com",
        "mailbucket.org",
        "mailchop.com",
        "mailcatch.com",
        "maildrop.cc",
        "maildrop.cf",
        "maildrop.ga",
        "maildrop.gq",
        "maildrop.ml",
        "maileater.com",
        "mailexpire.com",
        "mailf5.com",
        "mailfall.com",
        "mailfreeonline.com",
        "mailguard.me",
        "mailin8r.com",
        "mailinater.com",
        "mailinator.com",
        "mailinator.net",
        "mailinator.org",
        "mailinator2.com",
        "mailinbox.co",
        "mailinbox.com",
        "mailismagic.com",
        "mailjunk.cf",
        "mailjunk.ga",
        "mailjunk.gq",
        "mailjunk.ml",
        "mailjunk.tk",
        "mailme.gq",
        "mailme.ir",
        "mailme24.com",
        "mailmetrash.com",
        "mailmoat.com",
        "mailnew.com",
        "mailnesia.com",
        "mailnull.com",
        "mailonaut.com",
        "mailops.com",
        "mailopened.com",
        "mailpick.biz",
        "mailproxsy.com",
        "mailquack.com",
        "mailrock.biz",
        "mailscrap.com",
        "mailshell.com",
        "mailsiphon.com",
        "mailslapping.com",
        "mailslite.com",
        "mailsoul.com",
        "mailtome.de",
        "mailtothis.com",
        "mailtrash.net",
        "mailtv.net",
        "mailtv.tv",
        "mailzilla.com",
        "mailzilla.org",
        "makemetheking.com",
        "manifestgenerator.com",
        "manybrain.com",
        "mbx.cc",
        "mega.zik.dj",
        "meltmail.com",
        "messagebeamer.de",
        "mezimages.net",
        "miaferrari.com",
        "migumail.com",
        "mindless.com",
        "mintemail.com",
        "misterpinball.de",
        "mjukglass.nu",
        "moaktmail.com",
        "mohmal.com",
        "mooo.com",
        "moot.es",
        "motormania.com.ua",
        "mozartmail.com",
        "msa.minsmail.com",
        "msgos.com",
        "mt2009.com",
        "mt2014.com",
        "mucincanon.com",
        "muelmail.com",
        "myfake.ru",
        "mymail-in.net",
        "mymailoasis.com",
        "mynetstore.de",
        "mypacks.net",
        "mypartyclip.de",
        "myphantomemail.com",
        "myspaceinc.com",
        "myspaceinc.net",
        "myspaceinc.org",
        "myspacepimpedup.com",
        "mytemp.email",
        # N
        "nabuma.com",
        "nada.email",
        "nada.ltd",
        "nal.net",
        "netmails.com",
        "netmails.net",
        "netzidiot.de",
        "nevermail.de",
        "newfilter.cf",
        "nice-4u.com",
        "nincsmail.hu",
        "no-spam.ws",
        "nobulk.com",
        "noclickemail.com",
        "nodezine.com",
        "nogmailspam.info",
        "nomail.pw",
        "nomail.xl.cx",
        "nomail2me.com",
        "nomorespamemails.com",
        "nonspam.eu",
        "nonspammer.de",
        "noref.in",
        "nospam.ze.tc",
        "nospam4.us",
        "nospamfor.us",
        "nospammail.net",
        "nospamthanks.info",
        "notmailinator.com",
        "notsharingmy.info",
        "nowhere.org",
        "nwldx.com",
        # O
        "odaymail.com",
        "oe788.com",
        "ohaaa.de",
        "omail.pro",
        "omgmail.org",
        "one-time.email",
        "oneoffmail.com",
        "onewaymail.com",
        "online.ms",
        "oopi.org",
        "opayq.com",
        "ora.um.la",
        "orangotango.cf",
        "ordinaryamerican.net",
        "otherinbox.com",
        "otherinbox.comdisposeable.com",
        "ourklips.com",
        "owlpic.com",
        # P
        "pepbot.com",
        "petrzilka.net",
        "pfui.ru",
        "photo-impact.eu",
        "phpbb.uu.gl",
        "pimpedupmyspace.com",
        "pjjkp.com",
        "plexolan.de",
        "poczta.onet.pl",
        "politikerclub.de",
        "polyfaust.com",
        "poofy.org",
        "pookmail.com",
        "postacı.cf",
        "postacı.ga",
        "postacı.gq",
        "postacı.ml",
        "postacı.tk",
        "powered.name",
        "privy-mail.com",
        "privy-mail.de",
        "privymail.de",
        "proxymail.eu",
        "prtnx.com",
        "prtz.eu",
        "punkass.com",
        "puttana.cf",
        "puttana.ga",
        "puttana.gq",
        "puttana.ml",
        # Q - R
        "q00.me",
        "q2rjp.com",
        "qacmjeq.com",
        "qoika.com",
        "qq.com.hate.email",
        "r4nd0m.de",
        "raketenmann.de",
        "rancidit.com",
        "rcpt.at",
        "re-gister.com",
        "reallymymail.com",
        "rechner.cx",
        "recyclemail.dk",
        "redfeathercrow.com",
        "regbypass.com",
        "regbypass.comsafe-mail.net",
        "rejectmail.com",
        "rejectmail.us",
        "renraku.in",
        "rhyta.com",
        "riddles-unlocker.com",
        "rklips.com",
        "rmqkr.net",
        "rn.com",
        "rocketmail.com",  # Note: legitimate but often misused — kept for coverage
        "rotaniliam.com",
        "rppkn.com",
        "rsvhr.com",
        "rubyridge.com",
        "rumgel.com",
        "ruu.kr",
        # S
        "safetymail.info",
        "safetypost.de",
        "sandelf.de",
        "saynotospams.com",
        "scatmail.com",
        "schafmail.de",
        "schrott-email.de",
        "securehost.com.es",
        "seersmail.me",
        "selfdestructingmail.com",
        "senseless-entertainment.com",
        "services391.com",
        "sharedmailbox.org",
        "sharklasers.com",
        "shieldedmail.com",
        "shiftmail.com",
        "shitmail.me",
        "shitmail.org",
        "shitware.nl",
        "shmiland.com",
        "shortmail.net",
        "sibmail.com",
        "sinnlos-mail.de",
        "siteposter.net",
        "skeefmail.com",
        "slapsfromlastnight.com",
        "slaskpost.se",
        "slave-auctions.net",
        "slopsbox.com",
        "slowmail.net",
        "smellfear.com",
        "smwg.info",
        "snakemail.com",
        "sneakemail.com",
        "sneakmail.de",
        "snkmail.com",
        "sofimail.com",
        "sofort-mail.de",
        "sogetthis.com",
        "somail.com",
        "soratemple.com",
        "sougade.com",
        "spam.la",
        "spam.su",
        "spam4.me",
        "spamail.de",
        "spambob.com",
        "spambob.net",
        "spambob.org",
        "spambog.com",
        "spambog.de",
        "spambog.ru",
        "spambox.info",
        "spambox.irishspringrealty.com",
        "spambox.us",
        "spamcannon.com",
        "spamcannon.net",
        "spamcero.com",
        "spamcon.org",
        "spamcorptastic.com",
        "spamcowboy.com",
        "spamcowboy.net",
        "spamcowboy.org",
        "spamday.com",
        "spamex.com",
        "spamfree.eu",
        "spamfree24.de",
        "spamfree24.eu",
        "spamfree24.info",
        "spamfree24.net",
        "spamfree24.org",
        "spamgoes.in",
        "spamgourmet.com",
        "spamgourmet.net",
        "spamgourmet.org",
        "spamherelots.com",
        "spamherelots.com",
        "spamhereplease.com",
        "spamhole.com",
        "spamify.com",
        "spaminbox.com",
        "spamit.ro",
        "spamkill.info",
        "spaml.com",
        "spaml.de",
        "spammotel.com",
        "spammy.host",
        "spamnot.com",
        "spamoff.de",
        "spamslicer.com",
        "spamspot.com",
        "spamthis.co.uk",
        "spamthis.network",
        "spamthisplease.com",
        "spamtrap.ro",
        "spamtrex.com",
        "spamui.com",
        "spamwc.cf",
        "spamwc.de",
        "spamwc.ga",
        "spamwc.gq",
        "spamwc.ml",
        "spamwc.net",
        "spamwc.org",
        "spamwc.tk",
        "spamzombies.com",
        "speedymail.org",
        "spoofmail.de",
        "stuffmail.de",
        "super-auswahl.de",
        "supergreatmail.com",
        "supermailer.jp",
        "superrito.com",
        "superstachel.de",
        "suremail.info",
        "svk.jp",
        # T
        "tafmail.com",
        "tagyourself.com",
        "talkinator.com",
        "tapchief.com",
        "teewars.org",
        "temp-link.net",
        "temp-mail.de",
        "temp-mail.io",
        "temp-mail.org",
        "temp-mail.ru",
        "temp.bart.nl",
        "temp.emeraldwebmail.com",
        "temp.headstrong.de",
        "tempail.com",
        "tempalias.com",
        "tempe-mail.com",
        "tempemail.biz",
        "tempemail.com",
        "tempemail.co.za",
        "tempemail.net",
        "tempinbox.co.uk",
        "tempinbox.com",
        "tempmail.com",
        "tempmail.de",
        "tempmail.eu",
        "tempmail.it",
        "tempmail.net",
        "tempmail.org",
        "tempmail.us",
        "tempmailer.com",
        "tempmailer.de",
        "tempomail.fr",
        "temporarily.de",
        "temporarioemail.com.br",
        "temporaryemail.net",
        "temporaryemail.us",
        "temporaryforwarding.com",
        "temporaryinbox.com",
        "temporarymailaddress.com",
        "tempsky.com",
        "tempthe.net",
        "tempymail.com",
        "thankyou2010.com",
        "thecloudindex.com",
        "thelightningmail.net",
        "thenagus.com",
        "theoneandonlydiscordmail.com",
        "thex.ro",
        "throwam.com",
        "throwaway.email",
        "throwaway.io",
        "throwam.com",
        "throwam.net",
        "throwamailbox.com",
        "tinyurl24.com",
        "tmailinator.com",
        "toiea.com",
        "toomail.biz",
        "top-mailer.net",
        "tradermail.info",
        "trash-mail.at",
        "trash-mail.com",
        "trash-mail.de",
        "trash-mail.ga",
        "trash-mail.io",
        "trash-mail.ml",
        "trash-mail.net",
        "trash-mail.org",
        "trash-mail.xyz",
        "trashemail.de",
        "trashinbox.com",
        "trashmail.at",
        "trashmail.com",
        "trashmail.de",
        "trashmail.io",
        "trashmail.me",
        "trashmail.net",
        "trashmail.org",
        "trashmail.xyz",
        "trashmailer.com",
        "trashspam.com",
        "trbvm.com",
        "trickmail.net",
        "trillianpro.com",
        "trmailbox.com",
        "trollmail.me",
        "tropicalbass.info",
        "trungtamtuvan.com",
        "ttszuo.xyz",
        "twinmail.de",
        "tyldd.com",
        # U
        "uggsrock.com",
        "unamed.de",
        "unids.com",
        "unimark.org",
        "unimail.uni.de",
        "unlimit.com",
        "upliftnow.com",
        "uplipht.com",
        "urhen.com",
        "uroid.com",
        "username.e4ward.com",
        # V
        "venompen.com",
        "veryrealemail.com",
        "vickaentb.cf",
        "vickaentb.ga",
        "vickaentb.gq",
        "vickaentb.ml",
        "vickaentb.tk",
        "viewcastmedia.com",
        "viewcastmedia.net",
        "viewcastmedia.org",
        "viralplays.net",
        "vkcode.ru",
        "vomoto.com",
        "vpn.st",
        # W
        "wazabi.club",
        "webemail.me",
        "weg-werf-email.de",
        "wegwerf-email.at",
        "wegwerf-email.de",
        "wegwerf-email.net",
        "wegwerf-email.org",
        "wegwerfadresse.de",
        "wegwerfemail.com",
        "wegwerfemail.de",
        "wegwerfemail.info",
        "wegwerfemail.net",
        "wegwerfemail.org",
        "wegwerfmail.de",
        "wegwerfmail.info",
        "wegwerfmail.net",
        "wegwerfmail.org",
        "wetrainbayarea.com",
        "wetrainbayarea.org",
        "wh4f.org",
        "whyspam.me",
        "willhackforfood.biz",
        "willselfdestruct.com",
        "winemaven.info",
        "wronghead.com",
        "wuzup.net",
        "wuzupmail.net",
        # X - Y - Z
        "xagloo.com",
        "xemaps.com",
        "xents.com",
        "xmaily.com",
        "xoxy.net",
        "yaho.com",
        "yahomail.com",
        "yep.it",
        "yepmail.net",
        "yodx.ro",
        "yopmail.com",
        "yopmail.fr",
        "yopmail.net",
        "yopmail.org",
        "yopmail.pp.ua",
        "youmail.ga",
        "yourdomain.com",
        "yourfake.email",
        "yuurok.com",
        "zain.site",
        "zed.org",
        "zerotohero.guru",
        "zetmail.com",
        "zoemail.com",
        "zoemail.net",
        "zoemail.org",
        "zomg.info",
    }
)


def _get_allowed_domains() -> frozenset[str]:
    """Return the set of domains that override the blocklist.

    Read from the ``ALLOWED_EMAIL_DOMAINS`` environment variable,
    which is a comma-separated list of lowercase domain names.

    Returns
    -------
    frozenset[str]
        Set of domain names that should bypass blocklist checking.
        Empty frozenset if the env var is not set or is empty.
    """
    raw = os.environ.get("ALLOWED_EMAIL_DOMAINS", "").strip()
    if not raw:
        return frozenset()
    return frozenset(d.strip().lower() for d in raw.split(",") if d.strip())


def get_email_domain(email: str) -> str:
    """Extract the lowercased domain part from an email address.

    Parameters
    ----------
    email:
        A well-formed email address (e.g., ``user@example.com``).

    Returns
    -------
    str
        The domain portion, lowercased (e.g., ``"example.com"``).

    Raises
    ------
    ValueError
        If the email does not contain exactly one ``@`` character.
    """
    parts = email.split("@")
    if len(parts) != 2 or not parts[1]:
        raise ValueError(f"Invalid email address: {email!r}")
    return parts[1].lower()


def is_disposable_email(email: str) -> bool:
    """Return True if the email's domain is on the disposable domain blocklist.

    Parameters
    ----------
    email:
        The email address to check. Case-insensitive domain comparison.

    Returns
    -------
    bool
        True if the domain is a known disposable/temporary email provider.

    Raises
    ------
    ValueError
        If the email format is invalid (no ``@`` character).

    Notes
    -----
    - Domain check is O(1) — uses a frozenset membership test.
    - Override via ``ALLOWED_EMAIL_DOMAINS`` env var for internal testing.
    - Uses :func:`get_email_domain` for parsing (raises ValueError on bad format).

    Example
    -------
    ::

        if is_disposable_email("user@mailinator.com"):
            raise HTTPException(
                status_code=400,
                detail="Please use a permanent email address",
            )
    """
    domain = get_email_domain(email)

    # Check the allowlist override first (env var for testing/internal use)
    allowed_domains = _get_allowed_domains()
    if domain in allowed_domains:
        logger.debug("Email domain %r is in ALLOWED_EMAIL_DOMAINS — bypassing blocklist", domain)
        return False

    is_blocked = domain in DISPOSABLE_DOMAINS
    if is_blocked:
        logger.warning("Bot prevention: disposable email domain blocked: %r", domain)
    return is_blocked
