"use client";

/**
 * AIDisclosureBanner — Oregon SB 1546 / FTC AI disclosure compliance.
 *
 * Displays a non-intrusive but clearly visible notice that the user is
 * interacting with an AI assistant, not a human. Required by:
 *   - Oregon SB 1546 (chatbot disclosure for minors, gaming/COPPA overlap)
 *   - FTC AI disclosure guidelines (unfair/deceptive acts, 15 U.S.C. 45)
 *
 * Placement: pinned below the DashboardHeader, above the chat stream.
 * Dismissible per session (localStorage key: dd_ai_disclosure_dismissed_<sessionId>).
 * Re-appears on every new session to satisfy the "at start of session" requirement.
 *
 * Accessibility: role="status", aria-live="polite", sufficient contrast ratio.
 */

import { useState, useEffect } from "react";
import { Info, X } from "lucide-react";
import { cn } from "@/lib/utils";

export interface AIDisclosureBannerProps {
  /** Session ID — used to key dismissal state so it reappears on new sessions. */
  sessionId: string | null;
  /** Optional additional className on the outer container. */
  className?: string;
}

const STORAGE_KEY_PREFIX = "dd_ai_disclosure_dismissed_";

export function AIDisclosureBanner({
  sessionId,
  className,
}: AIDisclosureBannerProps) {
  const [dismissed, setDismissed] = useState(false);

  // Restore dismissal state for this specific session from localStorage.
  // A new sessionId means the user started a new session → show again.
  useEffect(() => {
    if (!sessionId) {
      setDismissed(false);
      return;
    }
    try {
      const stored = localStorage.getItem(STORAGE_KEY_PREFIX + sessionId);
      setDismissed(stored === "1");
    } catch {
      // localStorage may be unavailable (SSR, private mode) — default to visible
      setDismissed(false);
    }
  }, [sessionId]);

  const handleDismiss = () => {
    setDismissed(true);
    if (sessionId) {
      try {
        localStorage.setItem(STORAGE_KEY_PREFIX + sessionId, "1");
      } catch {
        // ignore
      }
    }
  };

  if (dismissed) return null;

  return (
    <div
      role="status"
      aria-live="polite"
      aria-label="AI disclosure notice"
      data-testid="ai-disclosure-banner"
      className={cn(
        // Layout
        "flex items-start gap-2.5 px-4 py-2.5",
        // Info-blue colour palette — distinct from gold (agent) and red (error)
        "bg-blue-950/60 border-b border-blue-700/40",
        // Text
        "text-blue-200",
        className
      )}
    >
      {/* Icon */}
      <Info
        className="h-4 w-4 mt-0.5 flex-shrink-0 text-blue-400"
        aria-hidden="true"
      />

      {/* Disclosure text */}
      <p className="flex-1 text-xs leading-relaxed font-body">
        <span className="font-semibold text-blue-100">AI Notice:</span>{" "}
        You are chatting with an AI assistant. This is not a human.
        Responses are generated by artificial intelligence and may not
        always be accurate.
      </p>

      {/* Dismiss button */}
      <button
        onClick={handleDismiss}
        aria-label="Dismiss AI disclosure notice"
        className={cn(
          "flex-shrink-0 p-0.5 rounded",
          "text-blue-400 hover:text-blue-200 hover:bg-blue-800/50",
          "transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-1 focus:ring-offset-blue-950"
        )}
      >
        <X className="h-3.5 w-3.5" aria-hidden="true" />
      </button>
    </div>
  );
}
