"""Pydantic schemas for message request/response models.

Defines the API-facing DTOs for sending messages to the agent and
receiving governed responses.
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

__all__ = [
    "ActionCard",
    "MessageRequest",
    "MessageResponse",
]


class ActionCard(BaseModel):
    """A structured UI card returned alongside an agent response.

    Produced by the skill execution pipeline and consumed by the frontend
    to render rich inline cards (KPI, calendar, confirmation, etc.).
    """

    type: str = Field(description="Card type matching frontend CardPayload.type")
    data: dict = Field(default_factory=dict, description="Card-specific payload data")
    skill: str = Field(default="", description="Skill that produced this card")
    action: str = Field(default="", description="Action that was executed")


class MessageRequest(BaseModel):
    """Request body for sending a message to an agent session.

    Attributes
    ----------
    content:
        The user's text message (1–10 000 characters).
    """

    content: str = Field(
        ...,
        min_length=1,
        max_length=10_000,
        description="The user's text message.",
    )
    attachments: list[dict] | None = Field(
        default=None,
        description="Optional file attachments: [{file_id, file_url, file_name, content_type}]",
    )


class MessageResponse(BaseModel):
    """Response from the agent after processing a message.

    Attributes
    ----------
    content:
        The agent's text response.
    session_id:
        The session this response belongs to.
    model_used:
        Identifier of the LLM model that generated the response.
    input_tokens:
        Number of input tokens consumed by the LLM call.
    output_tokens:
        Number of output tokens generated by the LLM call.
    governance_decision:
        The governance verdict: "PROCEED", "REVIEW", or "HALT".
    convergence_status:
        Budget consumption status: "WITHIN_BUDGET", "WARNING", or "BUDGET_EXCEEDED".
    halted:
        True if the response was blocked by governance (no LLM call made).
    """

    content: str
    session_id: str
    model_used: str
    input_tokens: int = 0
    output_tokens: int = 0
    governance_decision: str = "PROCEED"
    convergence_status: str = "WITHIN_BUDGET"
    halted: bool = False
    actions: list[ActionCard] = Field(
        default_factory=list,
        description="Structured action cards to render alongside the text response",
    )
